name: stylua
on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/**"

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check --config-path=.stylua.toml lua/
